### ISSUE TITLE
ExecuteOnBuild File Property

### ISSUE THREAD

**Issue by Mike-EEE** [bennor/AutoT4#3] opened 2014-11-30 14:46 UTC
Love this extension... thank you!  I was curious if you could possibly add an extension property on the files property list (call it ExecuteOnBuild) that allows you to turn on/off template execution on build on a file-by-file basis.

**Comment by VagyokC4** [comment] 2015-01-28 18:20
Has this been implemented yet?  I would like to ONLY turn on this feature with certain .TT files, not just a blanket Auto Transform.

**Comment by bennor** [comment] 2015-01-28 22:36
I have implemented this but have not pushed it (or merged with master). I will do it on Saturday.

**Comment by Michael-DST** [comment] 2015-01-28 22:37
Coooool. :)

**Comment by bennor** [comment] 2015-01-29 10:52
@Michael-DST & @VagyokC4: If you feel like being testers for me, the VSIX is available now from the [releases page for v1.1.0](https://github.com/bennor/AutoT4/releases/tag/v1.1.0). 

Let me know if you run into any problems (or if it just doesn't work for some reason).

**Comment by malylemire1** [comment] 2015-01-30 17:19
I've just tested the 1.1.0.
VS2013 get restarted most of the time I edit a T4 with Run on build set to False.

I must mention that I use Tangible T4 editor but Transform on build is set to false.
By the way thanks a lot for this new feature!
It was just what I was looking for.

Maly

**Comment by bennor** [comment] 2015-01-30 21:59
Okay, so clearly still needs work. I will have a look at it later today.

**Comment by VagyokC4** [comment] 2015-01-30 23:59
I've experienced no problems with 1.1.0.  Its seems to be working as expected for me :+1:

**Comment by bennor** [comment] 2015-01-31 00:01
There's definitely some sort of problem with it. In some circumstances it seems to completely crash VS, but I can't reproduce it reliably enough to figure out what's happening and the error above points to a missing `null` check somewhere but I can't find anything that I'm not checking.

**Comment by VagyokC4** [comment] 2015-01-31 00:05
What do you think about reversing the default logic.. so that Run on build defaults to false, and you selectively turn ON which files should be automatically transformed on build?

**Comment by bennor** [comment] 2015-01-31 00:07
I'm not real keen on that. The great thing about it from my point of view is that you install it and in most cases don't have to think about it -- it just works without any configuration.

**Comment by Michael-DST** [comment] 2015-01-31 00:09
Make the default setting/behavior read from a setting in app.config?

**Comment by Michael-DST** [comment] 2015-01-31 00:10
Or actually... not app.config, but from the .csproj file.

**Comment by VagyokC4** [comment] 2015-01-31 00:11
Yes I can see that use case i.e. zero configuration, but I tend to want to 'first do no harm' and since TT files can automatically do a lot of stuff, I can also see the use case of 'Install AutoTT' and tell your TT files to 'Run on Build'.  Then installing AutoTT without any user interaction will 'first do no harm'

just my two pennies :)

**Comment by malylemire1** [comment] 2015-07-09 18:03
I've just found the problem.
The finalizer in AutoT4Extender was calling dispose on an already finalized object.
It's seem that calling dispose in the finalizer was also leading to twice disposal.

To correct the problem simply put this in the finalizer with a proper error message.

~AutoT4Extender()
        {
            try
            {
                if (_extenderSite != null)
                    _extenderSite.NotifyDelete(_cookie);
            }
            catch
            {

            }
        }

You can remove the IDisposable implementation as it will never be called.

**Comment by bennor** [comment] 2015-07-09 20:28
Amazing, thanks. Do you mind submitting a PR for the bug fix?

I'm not keen on changing the default behaviour because it should _just work_ for simple cases, but I can probably help you out. I'll add a 4th option `Default` or `Inherit `, then give you the option to change the default behaviour from the VS options dialog.

**Comment by malylemire1** [comment] 2015-07-10 14:13
Done with the PR.

Thanks would be great to have this setting.

**Comment by bennor** [comment] 2015-07-14 11:09
The latest release should work, and has the additional option to change the default from "Before build" to "After  build" or "Disabled".

https://github.com/bennor/AutoT4/releases/tag/v1.2.0

**Comment by bennor** [comment] 2015-07-14 11:09
If nobody reports any problems with that build, I'll push it up to the gallery soon.

**Comment by malylemire1** [comment] 2015-07-14 18:08
Solution folders were not scanned for templates.
Added a PR to support this.

**Comment by bennor** [comment] 2017-03-22 10:50
Closing since the core work is done and the one remaining issue has been raised independently.

**Closed by bennor** 2017-03-22 10:50 UTC
Labels: enhancement
