### ISSUE TITLE
When will the latest get pushed to Nuget?

### ISSUE THREAD

**Issue by VagyokC4** [bennor/AutoT4#6] opened 2015-02-10 00:34 UTC
Have all the bugs been worked out?  I've noticed lately my VS crashing lately when I click on a TT file..  Not sure if AutoT4 is the cause or not?

**Comment by bennor** [comment] 2015-02-10 00:37
AutoT4 isn't a NuGet package, so but I will push it to the VS Gallery when I've had time to look at the bug. At this stage, I'm not sure if I'll have time to get to it until the end of February - I'm flat out this week with the day job and on holiday next week.

You are welcome to try and track down the problem yourself and submit a PR if you want :trollface:

**Comment by bennor** [comment] 2015-07-14 11:13
This is a duplicate of #9 (even though it was raised first), and will be addressed by #3.

**Closed by bennor** 2015-07-14 11:13 UTC
